/**
 * Auto-generated migration map for auth-pages
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration auth-pages
 */

import * as Generated from '@autional/shared/generated/api';

export const getMFAStatus = Generated.mfaStatusByStatus;
export const setupMFA = Generated.mfaTotpDevicesPost;
export const enableMFA = Generated.mfaTotpEnablePost;
export const verifyTOTPMFA = Generated.mfaTotpVerifyPost;
export const disableMFA = Generated.mfaTotpDisablePost;
export const regenerateBackupCodes = Generated.mfaBackupCodesGeneratePost;
export const validateTOTP = Generated.mfaTotpValidatePost;
export const sendMFASMS = Generated.mfaSmsSendPost;
export const verifyMFASMS = Generated.mfaSmsVerifyPost;
export const disableMFASMS = Generated.mfaSmsDisablePost;
export const sendMFAEmail = Generated.mfaEmailSendPost;
export const verifyMFAEmail = Generated.mfaEmailVerifyPost;
export const disableMFAEmail = Generated.mfaEmailDisablePost;
export const getMFARiskPolicy = Generated.adminMfaRiskPolicy;
export const getOAuthProviders = Generated.authOauthProviders;
export const initiateOAuth = Generated.authOauthByOauth;
export const verifyMFA = Generated.mfaBackupCodesVerifyPost;
export const verifyMFAChallenge = Generated.authMfaVerifyChallengePost;
export const getOAuthClient = Generated.oauthClientByClient;

// @generated-api-exempt: uses raw fetch() for redirect:manual handling (not supported by axios)
export const authorizeOAuth = (data: Record<string, unknown>) => {
	return fetch('/bff/oauth/api/v1/oauth/authorize', {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify(data),
		redirect: 'manual',
	}).then((res) => {
		const loc = res.headers.get('Location');
		if (loc) return { data: { redirect_url: loc } };
		return res.json().then((j) => ({ data: j }));
	});
};
export const initiateSSO = Generated.authSsoInitiatePost;
export const beginPasskeyLogin = Generated.authWebauthnLoginBeginPost;
export const completePasskeyLogin = Generated.authWebauthnLoginCompletePost;
export const beginPasskeyRegister = Generated.authWebauthnRegisterBeginPost;
export const completePasskeyRegister = Generated.authWebauthnRegisterCompletePost;
// MISSING in generated: deleteAccount (DELETE /auth/me)
export const changePassword = Generated.authMePasswordPut;
export const updateProfile = Generated.authMePut;
export const getMe = Generated.authMe;
export const sendSmsCode = Generated.authSendSmsCodePost;
export const verifyPhone = Generated.authVerifyPhonePost;
export const exchangeCodeForToken = Generated.authOauthCallbackByOauth;
export const mfaPushChallengePost = Generated.mfaPushChallengePost;
export const mfaPushChallengeByChallenge = Generated.mfaPushChallengeByChallenge;
